### ISSUE TITLE
Adding gits reset workflow support

### ISSUE THREAD

**Issue by tanay105** [amolgautam25/GITS#6]
GITS reset : 
no need to get confused with --soft and --hard , it will just sync everything with origin/master.  Final repo state should be such that ,origin/master  and local master are all in sync. It can be used on any branch and not just master. I have just used the master branch as an example.

**Comment by amolgautam25** [comment]
please refer to this : https://stackoverflow.com/questions/9301782/need-to-reset-git-branch-to-origin-version
